services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    container_name: backend
    # env_file:
    #   - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:80"

  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_DB: crypto_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
