FROM node:18 AS build
WORKDIR /app
COPY . /app
RUN npm install && npm run build

FROM nginx:alpine
# COPY --from=build /app/dist /usr/share/nginx/html
COPY ./index.html /usr/share/nginx/html/index.html
EXPOSE 80
